#!/bin/sh
#
# Starts 
#
ExecScript=/soc/scripts/usb-adb.sh

start() {
	printf "Starting $ExecScript"
    bash -c ". /etc/profile ; /soc/scripts/usb-adb.sh start"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping $ExecScript"
    # /etc/rc.local stop
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
