#!/bin/sh
#
# Starts 
#
ExecScript=ledtrig-heartbeat

start() {
	printf "Starting $ExecScript"
    modprobe ledtrig-heartbeat
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping $ExecScript"
    rmmod ledtrig-heartbeat
    # /etc/rc.local stop
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
